name: Auto Run Script

on:
  schedule:
    - cron: '*/5 * * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Run autorun.sh
        run: |
          chmod +x ./autorun.sh
          ./YT2m/autorun.sh

      - name: Add changes
        run: git add -A

      - name: Check for changes
        id: changes
        run: |
          if git diff-index --quiet HEAD --; then echo "::set-output name=result::no"; else echo "::set-output name=result::yes"; fi

      - name: Commit & push
        if: steps.changes.outputs.result == 'yes'
        run: |
          git commit -m "links are updated"
          git push -f
