name: M3U generator

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Main
        run: |
          pwd
          chmod +x autorun.sh
          ./autorun.sh

      - name: git add
        run: |
          git add -A
          ls -la

      - name: Check for changes
        id: changes
        run: |
          if git diff-index --quiet HEAD --; then echo "no changes"; else echo "changes"; fi
        continue-on-error: true

      - name: commit & push
        if: steps.changes.outputs.result == 'changes'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git commit -m "links are updated"
          git push https://github-actions[bot]:${{ secrets.PAT_TOKEN }}@github.com/shinch58/YT2m.git
