name: Upload M3U8 URLs to SFTP

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if y04.m3u8 exists
        run: |
          echo "Checking if y04.m3u8 file exists"
          ls -la y04.m3u8
          cat y04.m3u8 || echo "y04.m3u8 file does not exist or is empty"

      - name: Extract URLs from M3U8 and generate i.php
        run: |
          echo "Extracting URLs from y04.m3u8"
          if grep -oP '(?<=#EXTINF:.*",https://).*(?=m3u8)' y04.m3u8 | sed 's/^/https:\/\/&m3u8/' > i.php; then
            echo "URLs successfully extracted and i.php file created"
            cat i.php
          else
            echo "Failed to extract URLs or create i.php file"
            exit 1
          fi

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Upload i.php to SFTP
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          echo "Uploading i.php to SFTP"
          sshpass -p $SFTP_PASSWORD sftp -o StrictHostKeyChecking=no $SFTP_USERNAME@$SFTP_SERVER <<EOF
          put i.php /path/to/remote/i.php
          bye
